# Generated by Django 4.0.4 on 2022-04-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_user_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Customer',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
