# Generated by Django 4.0.4 on 2022-04-12 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_customer_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.customer'),
        ),
    ]
