# Generated by Django 4.0.4 on 2022-04-12 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_product_customer_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
