# Generated by Django 4.0.4 on 2022-04-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Customer',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
    ]
