# Generated by Django 4.0.4 on 2022-04-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_user_productorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='user',
            field=models.CharField(default='', max_length=140),
        ),
    ]
