# Generated by Django 4.0.4 on 2022-04-12 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='Order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.customer'),
        ),
    ]
