# Generated by Django 4.0.4 on 2022-04-12 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_productorder_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='user',
        ),
    ]
