# Generated by Django 4.0.4 on 2022-04-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='Status',
            field=models.CharField(blank=True, choices=[('a', 'Pirkti'), ('p', 'Rezervuoti')], default='a', help_text='Statusas', max_length=1),
        ),
    ]
