# Generated by Django 4.0.4 on 2022-04-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/python.png', upload_to='products'),
        ),
    ]
