# Generated by Django 4.0.4 on 2022-04-12 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
